CREATE TABLE IF NOT EXISTS `accounts` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `type` tinyint(1) NOT NULL,
    `active` tinyint(1) NOT NULL,
    `username` varchar(50) NOT NULL,
    `password` varchar(128) NOT NULL,
    `administrator` tinyint(1) NOT NULL,
    `firstname` varchar(50) NOT NULL,
    `lastname` varchar(50) NOT NULL,
    `email` varchar(50) NOT NULL,
    `website` varchar(200),
    `image` varchar(50),
    `institution` varchar(50),
    `institution_image` varchar(50),
    `expertise` varchar(300),
    `instrumentation` text,
    `biography` text,
    `created` datetime NOT NULL,
    PRIMARY KEY (`id`)
);